### PR TITLE
Fixed a bucket of lava disappearing when used in a furnace

### LINKED ISSUE #2385: Lava bucket disappeared when using Furnace
### Issue description

Putting a lava bucket in the Furnace will not leave the empty bucket as in Vanilla

- Expected result: I expect that the lava bucket will turn into empty bucket like Vanilla
- Actual result: Lava bucket is gone, along with the bucket

### Steps to reproduce the issue

1. Putting the Lava Bucket inside the Furnace
2. The Lava Bucket disappeared, not leaving any trace behind

### OS and versions

* PocketMine-MP:  3.1.4 commit 17f7dc3
* PHP: 7.2
* Server OS: Windows Server 2008 R2 64-bit
* Game version: PE/Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

### PR DESCRIPTION
**Pull request by Govdim**
## Introduction

This pull request fixes the disappearance of a lava bucket when used in a furnace.

It was a little strange to add a method for the sake of one item
But maybe someone wants to create custom items and this method will definitely come in handy :)

### Relevant issues

* Fixes #2385

### CODE REVIEW

File: src/pocketmine/item/Item.php [hunk 1]
```diff
@@ -655,6 +655,14 @@ public function getFuelTime() : int{
 		return 0;
 	}
 
+	/**
+	 * Returns an item after burning fuel
+	 */
+	public function getFuelResidue() : Item{
+		$this->pop();
```
Comment (dktapps) [inline src/pocketmine/item/Item.php:662]: This will produce unexpected behaviour when called multiple times. It should clone itself first.

**Review by dktapps — CHANGES_REQUESTED** [review]
Looks good, just some minor nits.

File: src/pocketmine/item/Item.php (hunk 1 above)
Comment (Govdim) [reply src/pocketmine/item/Item.php:662]: I also thought about it at first, but then I forgot XD

**Review by dktapps — APPROVED** [review]
