### PR TITLE
Separate sneak keydown flag from crouching flag

### LINKED ISSUE #6066: Crawling or swimming animation show up while jumping and sneaking at the same time, at a height of 2 blocks
### Issue description
Player animation showing crawling or swimming while attempting to jump while sneaking in a small space two blocks high
- Expected result: No animation
- Actual result: Animation show up for a split of a second then gone.

### Steps to reproduce the issue
1. Build up an upside down L
2. Sneak under the roof of that L, stay close to the wall
3. Jumping while sneaking
image

https://github.com/pmmp/PocketMine-MP/assets/54394881/1a7edff4-8201-4617-a4f3-ffb44a5e02d5

https://github.com/pmmp/PocketMine-MP/assets/54394881/60f0737a-f894-4b73-861d-212d6e610736

### OS and versions

* PocketMine-MP:
* PHP: 8.1
* Server OS: Win10
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

Plugins (2): DevTools v1.17.1, Test v0.0.1
Test does not change any things related to movements and entities

- If you remove all plugins, does the issue still occur? Yes

### LINKED ISSUE #6733: Phase Glitch
### Plugin information

Bug happens without plugins

### Problem description

- Steps to reproduce the issue: i do not completely know the actual way to reproduce it. but place a 1x1x2 square, with trapdoor or slab on top, and u can phase through. by spamming w key and space and shift. i also checked vanilla mc. vanilla mc doesnt even let u crouch while in the air like that

- Error backtraces: no error
- Crashdumps: no crashes
Plugin code that triggers the issue: none
List of installed plugins (use /plugins): none

Image
https://streamable.com/pbi5fr

i tried w slabs, couldnt phase

### Expected behaviour

not allow u to phase through the blocks

### PocketMine-MP version

5.28.2

### PHP version

8.2.27

### Server OS

Linux

### Game version (if applicable)

Windows 10, possibly others too

### PR DESCRIPTION
**Pull request by Dasciam**
### Related issues & PRs
fixes #6066
fixes #6733

### API changes

- `Player` now has `toggleSneakBindPressed` method to toggle sneak bind state
- `Player` now has `isSneakBindPressed` method to get toggle sneak bind state

### Behavioural changes

To determine whether player is actually sneaking for item/block interactions, BDS uses `PlayerAuthInputFlags::SNEAKING` , for player sneaking state only `PlayerAuthInputFlags::START_SNEAKING` and `PlayerAuthInputFlags::STOP_SNEAKING`.

This PR reverts #6544 changes due to incorrect flag usage

## Backwards compatibility

I don't know whether it can entail some BC break but it changes the `use item on` logic in `World` class

## Tests

First test: press crouch bind and release when you're forced to crouch
Be sure that you're not experiencing #6066 and #6733

https://github.com/user-attachments/assets/969bb4d1-ab5e-47a6-942b-c888d9171e88

Second test: press crouch bind while flying and place some interactable blocks
Be sure that you're experiencing #6544

https://github.com/user-attachments/assets/47b7dc71-0e01-407d-9fae-178d14e80a03

Third last test: carry some item in hand, press crouch bind and release when you're forced to crouch
- be sure that you can interact with door in that state
- press crouch bind
- you shouldn't be able to open and close the door
- select free slot
- you can interact with the door again (open and close)

https://github.com/user-attachments/assets/0f83189a-e2d6-46fb-acc4-68952a8178cd

### CODE REVIEW

**Comment by dktapps** [comment]
Probably worth reading https://github.com/pmmp/PocketMine-MP/issues/6548. The reason this wasn't already changed is because of the behavioural BC break of `isSneaking()`, since it wouldn't refer to pressing shift/disabling block interaction anymore, but rather if you were in a forced crouch state.

There are some other sneak-related issues that this might resolve.

**Comment by dktapps** [comment]
Also, there's probably other places where `isSneaking` would need to be changed

**Comment by Dasciam** [comment]
Perhaps this **protocol crap** should be removed from the player class?

I also doubt that `isSneaking` should be changed anywhere else in my opinion

I will definitely look for issues related to the sneaking state

**Comment by dktapps** [comment]
I think having it in the API is fine. The other option is that we'd have to pass the flag everywhere that needs it, and there's probably other things that do need it - e.g. events

The only thing I'm bothered about is that isSneaking changes meaning from "is pressing shift || is crouching" to just "is crouching". I don't like making behaviour changes like this.

That being said, there's a case to be made that plugins using isSneaking the old way were broken anyway from a player perspective, I suppose, so maybe people can won't mind

**Comment by Dasciam** [comment]
Can `PlayerToggleSneakEvent` have two values: `sneaking` and `sneakBindPressed`?

Also, maybe these changes could be in `major-next` instead of `minor-next`

**Comment by Dasciam** [comment]
So, `Player::toggleSneak` will accept next values: `sneaking` and `sneakBindPressed`

**Comment by dktapps** [comment]
It could go in major-next, but major-next won't be released for a while yet. Probably this is fine for minor-next, but I'll probably have to get some opinions from the team.

Not sure about `PlayerToggleSneakEvent` since it might confuse existing plugins. e.g. it could be called without `isSneaking()` changing at all if the player presses shift+space while flying in creative. Or it would be called without `isSneakBindPressed()` changing when popping out from underneath a 1.5 block space. But even just leaving it bound to `isSneaking()` alone already probably causes some disruption, since you can't really "toggle" `isSneaking()` that way anymore. Pretty confusing

**Comment by Dasciam** [comment]
Got you, a very hard thing to be honest

probably this PR also closes #6024

**Comment by dktapps** [comment]
Ok, I've had a think about this.

So, up to this point `isSneaking` and `PlayerToggleSneakEvent` have always reflected whether you were crouching, irrespective of the reason why. I think we should try to preserve this behaviour.
Yes, some plugins have probably used this to check whether the player was attempting to disable block-use, but perhaps it's not our responsibility to fix that. Such plugins would behave basically the same anyway - the only time they'd behave different would be when a player presses shift+space at the same time while flying (disabling use-block, but not crouching).

Possibly what we could do for `PlayerToggleSneakEvent` is to call it with `cancelled=true`, if the use-block input changes but the crouching state doesn't change. There are 2 cases I can think of that we'd need to beware of:

1) `pressSneak = false, crouching = unchanged` - if the player is under a slab (use-block changes, but doesn't stop crouching)
2) `pressSneak = true, crouching = unchanged` - if the player presses space followed by shift in creative (use-block changes, but doesn't start crouching)

**Comment by dktapps** [comment]
> Got you, a very hard thing to be honest
> 
> probably this PR also closes #6024

Yeah, for sure.
There's probably other sneak related issues that this probably fixes too.

**Comment by Dasciam** [comment]
Alright

**Comment by Dasciam** [comment]
I think it would be fine :smile_cat:

File: src/player/Player.php [hunk 1]
```diff
@@ -2075,11 +2080,17 @@ public function toggleSprint(bool $sprint) : bool{
 		return true;
 	}
 
-	public function toggleSneak(bool $sneak) : bool{
-		if($sneak === $this->sneaking){
+	public function toggleSneak(bool $sneak, bool $sneakBindPressed) : bool{
```
Comment (dktapps) [inline src/player/Player.php]: This is a BC break

File: src/player/Player.php [hunk 2]
```diff
@@ -2075,11 +2080,17 @@ public function toggleSprint(bool $sprint) : bool{
...
+		if($sneak === $this->sneaking && $sneakBindPressed === $this->sneakBindPressed){
 			return true;
 		}
-		$ev = new PlayerToggleSneakEvent($this, $sneak);
+
+		$ev = new PlayerToggleSneakEvent($this, $sneak, $sneakBindPressed);
+		if($sneak === $this->sneaking) {
+			$ev->cancel();
+		}
+		$this->sneakBindPressed = $sneakBindPressed;
```
Comment (dktapps) [inline src/player/Player.php]: Hmm. I suppose it's impossible to prevent someone from enabling this if done this way.

**Review by dktapps — COMMENTED** [review]
I don't love the `sneak bind pressed` terminology. I don't think it's very clear what it means.

`sneak pressed` would probably be fine, or possibly `use block disabled`.

File: src/player/Player.php (hunk 2 above)
Comment (Dasciam) [reply src/player/Player.php]: We can't prevent player's intention

File: src/player/Player.php (hunk 1 above)
Comment (Dasciam) [reply src/player/Player.php]: Alright

File: src/player/Player.php (hunk 2 above)
Comment (dktapps) [reply src/player/Player.php]: Well, we do allow cancelling all the other inputs (sneak, glide, swim etc).

I suppose there are easier ways to control this from an API perspective (e.g. `PlayerInteractEvent->setUseBlock()`). But it looks weird to do this directly before calling the event.

Comment (Dasciam) [reply src/player/Player.php]: I don't think this should be exposed to the developer, because this is pure player intention to hold sneak button and we don't want to modify this and we shouldn't

also, sneak, swim cancelling is making gameplay more buggy because the game haven't exposed any clear versatility with it

Comment (Dasciam) [reply src/player/Player.php]: But why not okay got it

Comment (Dasciam) [reply src/player/Player.php]: by versatility I mean we can cancel sneak but the client will try to sneak again and again till you release sneak button and not accepting new player state. Same with swimming

File: src/player/Player.php [hunk 3]
```diff
@@ -2075,12 +2084,18 @@ public function toggleSprint(bool $sprint) : bool{
...
 		}
-		$ev = new PlayerToggleSneakEvent($this, $sneak);
+
+		$ev = new PlayerToggleSneakEvent($this, $sneak, $sneakPressed);
+		if($sneak === $this->sneaking) {
+			$ev->cancel();
+		}
 		$ev->call();
+
+		$this->setSneakPressed($sneakPressed);
```
Comment (dktapps) [inline src/player/Player.php]: Better to put this before any event logic. Since it's not affected by the event.

File: src/player/Player.php [hunk 4]
```diff
@@ -1280,6 +1281,14 @@ public function isSpectator() : bool{
 		return $this->gamemode === GameMode::SPECTATOR;
 	}
 
+	public function setSneakPressed(bool $sneakPressed) : void{
+		$this->sneakPressed = $sneakPressed;
+	}
+
+	public function isSneakPressed() : bool{
```
Comment (dktapps) [inline src/player/Player.php:1292]: This should be documented to explain how it's different to `isSneaking()`

File: src/event/player/PlayerToggleSneakEvent.php [hunk 5]
```diff
@@ -32,12 +32,17 @@ class PlayerToggleSneakEvent extends PlayerEvent implements Cancellable{
...
+		protected bool $isSneakPressed
 	){
 		$this->player = $player;
 	}
 
 	public function isSneaking() : bool{
 		return $this->isSneaking;
 	}
+
+	public function isSneakPressed() : bool{
```
Comment (dktapps) [inline src/event/player/PlayerToggleSneakEvent.php:49]: This should be documented to explain how it differs from isSneaking()

File: src/event/player/PlayerToggleSneakEvent.php [hunk 6]
```diff
@@ -32,12 +32,24 @@ class PlayerToggleSneakEvent extends PlayerEvent implements Cancellable{
...
 	public function isSneaking() : bool{
 		return $this->isSneaking;
 	}
+
+	/**
+	 * Since 1.20.10, sneaking has multiple states that affects interacting with items/blocks.
+	 * isSneakPressed is different from isSneaking because is responsible for interaction limitation and don't change visual player state.
+	 * isSneaking is responsible for visual player state (hitbox height, sneaking).
+	 *
+	 * Returns true when the player is actually holding the sneak key.
```
Comment (dktapps) [inline src/event/player/PlayerToggleSneakEvent.php]: It'd be simpler to say something like

> Returns whether the player is pressing the sneak key.
> The player may still be sneaking even if this is false due to gameplay mechanics (e.g. releasing sneak while in a 1.5 block high space).

File: src/player/Player.php [hunk 7]
```diff
@@ -1280,6 +1281,21 @@ public function isSpectator() : bool{
...
+	}
+
+	/**
+	 * Since 1.20.10, sneaking has multiple states that affects interacting with items/blocks.
+	 * isSneakPressed is different from isSneaking because is responsible for interaction limitation and don't change visual player state.
+	 * isSneaking is responsible for visual player state (hitbox height, sneaking).
+	 *
+	 * Returns true when the player is actually holding the sneak key.
+	 */
+	public function isSneakPressed() : bool{
```
Comment (dktapps) [inline src/player/Player.php:1292]: As above

**Review by dktapps — DISMISSED** [review]

File: src/player/Player.php [hunk 8]
```diff
@@ -2075,12 +2088,18 @@ public function toggleSprint(bool $sprint) : bool{
...
-		if($sneak === $this->sneaking){
+	public function toggleSneak(bool $sneak, bool $sneakPressed = true) : bool{
+		if($sneak === $this->sneaking && $sneakPressed === $this->sneakPressed){
 			return true;
 		}
-		$ev = new PlayerToggleSneakEvent($this, $sneak);
+		$this->setSneakPressed($sneakPressed);
+
+		$ev = new PlayerToggleSneakEvent($this, $sneak, $sneakPressed);
+		if($sneak === $this->sneaking) {
```
Comment (dktapps) [inline src/player/Player.php]:
```suggestion
		if($sneak === $this->sneaking){
```

**Review by dktapps — COMMENTED** [review]
Looks basically fine now

**Review by dktapps — APPROVED** [review]

**Review by ipad54 — APPROVED** [review]
