### PR TITLE
Fix for explosions not removing tiles

### LINKED ISSUE #1450: explosions don't remove tiles

### PR DESCRIPTION
**Pull request by JackNoordhuis**
## Introduction
Prior to the commit below, blocks would be removed but any tiles attached to the block would remain (#1450).

### Relevant issues

* Fixes #1450

## Follow-up
Disclaimer: This does not fix tiles that have not been removed by previous explosions, you should use a plugin to achieve this.

## Tests
None – it's a pretty straightforward solution.

### CODE REVIEW

**Comment by dktapps** [comment]
This will degrade explosion performance, which is why I didn't do it like this myself. Whether the degradation is acceptable will require tests to see.

**Comment by Muqsit** [comment]
Maybe add a BlockEntity class and extend Chests, Furnaces, Skulls etc to the BlockEntity class?

**Comment by dktapps** [comment]
or an interface... I'm planning to add an interface like that anyway for automatic tile creation for relevant blocks.

**Comment by dktapps** [comment]
I'll test this later and see what the difference is like. Thanks for the PR.

**Comment by dktapps** [comment]
There is another problem here: the bug I tested was chest tiles not getting destroyed. When destroyed, they ought to drop their contents. This will simply delete them outright.

File: src/pocketmine/level/Explosion.php [hunk 1]
```diff
@@ -209,7 +213,20 @@ public function explodeB() : bool{
 
 			$t = $this->level->getTile($block);
 			if($t instanceof Tile){
```
Comment (Muqsit) [inline src/pocketmine/level/Explosion.php]: Better not call `Level::getTile()` if `$yieldDrops` is not true
```php
if($yieldDrops){
    $t = $this->level->getTile($block);
    if($t instanceof Container){
        //...
    }
}
```

Comment (dktapps) [reply src/pocketmine/level/Explosion.php]: @Muqsit and what about tiles that need to be removed which are not containers?

Comment (Muqsit) [reply src/pocketmine/level/Explosion.php]: updated.

**Comment by dktapps** [comment]
Looking good apart from some minor formatting issues.
