### PR TITLE
Fixed #32

### LINKED ISSUE #32: Loading chunk with invalid item causes a crash
### Issue description
For some reason sometimes when porting worlds from PC version or maybe converting format types. the item entities can be written on chunk nbt file wrong and cause crash when loading them.

### Steps to reproduce the issue
I Don't know and don't want to.

### OS and versions
* PocketMine-MP: Starting from 1.4 and up

### Crashdump, backtrace or other files
I added some debug messages in Item.php inside initEntity() and this is the output when invalid entity tries to get loaded.
```code
tried to spawn invalid item entity (minecraft:wooden_axe:0:1) at Position(level=mines,x=-226.93924904777,y=74.661162516132,z=113.17553093388)
tried to spawn invalid item entity (minecraft:glass_pane:0:1) at Position(level=mines,x=-227.12765333584,y=74.908027488115,z=113.33313738153)
```
I added temporary workaround for this
```php
if(!$this->namedtag->Item->id instanceof IntTag) {
	$this->level->removeEntity($this);
	return;
}
```
But this code above doesn't remove the entity record from nbt file.

This is the full error from console.
```
[22:56:03] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\item\Item::get() must be of the type integer, string given, called in /home/primus/DevField/src/pocketmine/nbt/NBT.php on line 110" (EXCEPTION) in "/src/pocketmine/item/Item" at line 283
[22:56:03] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[22:56:03] [Server thread/EMERGENCY]: Please upload the "/home/primus/DevField/CrashDump_Mon_Oct_17-22.56.03-EEST_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
```
And this is the dump string of that Item entity
```
["id"]=>
  object(pocketmine\nbt\tag\StringTag)#11871 (2) {
    ["__name":protected]=>
    string(2) "id"
    ["value":protected]=>
    string(17) "minecraft:feather"
  }
  ["Count"]=>
  object(pocketmine\nbt\tag\ByteTag)#11872 (2) {
    ["__name":protected]=>
    string(5) "Count"
    ["value":protected]=>
    int(1)
  }
  ["Damage"]=>
  object(pocketmine\nbt\tag\ShortTag)#11873 (2) {
    ["__name":protected]=>
    string(6) "Damage"
    ["value":protected]=>
    int(0)
  }

```

### PR DESCRIPTION
**Pull request by dktapps**
Seems in some PC worlds item ID is a string in the format "minecraft:blah" instead of a numeric ID. (Possibly 1.11?) This causes the crash described in #32 .

This has not been tested as I'm unable to obtain such a world which causes this issue. Please test and review.

### CODE REVIEW

File: src/pocketmine/nbt/NBT.php [hunk 1]
```diff
@@ -107,7 +107,13 @@ public static function getItemHelper(CompoundTag $tag){
 			return Item::get(0);
 		}
 
-		$item = Item::get($tag->id->getValue(), !isset($tag->Damage) ? 0 : $tag->Damage->getValue(), $tag->Count->getValue());
+		if($tag->id instanceof IntTag){
+			$item = Item::get($tag->id->getValue(), !isset($tag->Damage) ? 0 : $tag->Damage->getValue(), $tag->Count->getValue());
+		}else{ //PC item save format
```
Comment (SOF3) [inline src/pocketmine/nbt/NBT.php]: Not `elseif($tag->id instanceof StringTag)` for clarification? (And `else assert(false)` or `else throw new \RuntimeException` if IDEs complain)

Comment (dktapps) [inline src/pocketmine/nbt/NBT.php]: Is it really necessary? Under normal circumstances it's never going to be anything other than an int or string anyway.

**Comment by legoboy0215** [comment]
MCPC doesn't use Item IDs anymore.

**Comment by dktapps** [comment]
@PrimusLV could you test this and review?

**Comment by PrimusLV** [comment]
```
[Server thread/CRITICAL]: InvalidArgumentException: "Item CompoundTag ID must be an instance of StringTag or IntTag, pocketmine\nbt\tag\ShortTag given" (EXCEPTION) in "/src/pocketmine/nbt/NBT" at line 117
```

**Comment by dktapps** [comment]
My bad, fixed. Please retest.

**Comment by PrimusLV** [comment]
It should be
```php
if($tag->id instanceof IntTag or $tag->id instanceof ShortTag) {
```
or
```php
if(is_int($tag->id->getValue()) {
```

**Comment by dktapps** [comment]
Item IDs are ShortTags, not IntTags. My bad.

**Comment by PrimusLV** [comment]
Alright this commit is tested and works perfect.

**Comment by PrimusLV** [comment]
Just one more detail
```php
throw new \InvalidArgumentException("Item CompoundTag ID must be an instance of StringTag or IntTag, " . get_class($tag->id) . " given"); 
```

**Comment by dktapps** [comment]
Fixed

**Comment by archie426** [comment]
Merge please, looks ok

**Comment by SOF3** [comment]
@archie426 please use the review->approve button if you feel that it is OK, and explain from what perspective do you think it is OK (e.g. by testing, or by looking at code, etc.)

**Comment by archie426** [comment]
@SOF3 Oops, sorry
