### PR TITLE
Fix chorus not working below y 0

### LINKED ISSUE #5978: Chorus not working below y 0
### Issue description

- Expected result: In vanilla, chorus teleport player if it is below y 0
- Actual result: In pmmp, it's don't work

### Steps to reproduce the issue
1. take chorus
2. go beow y 0 and place solid block
3. use chorus fruit

### OS and versions

* PocketMine-MP: 5.4.2

### PR DESCRIPTION
**Pull request by DebHugo**
## Introduction

Fixes #5978 

### API changes

Modify the `onConsume` function in `Chorus Fruit`

### CODE REVIEW

File: src/item/ChorusFruit.php [hunk 1]
```diff
@@ -49,22 +49,24 @@ public function onConsume(Living $consumer) : void{
 
 		$origin = $consumer->getPosition();
 		$minX = $origin->getFloorX() - 8;
-		$minY = min($origin->getFloorY(), $consumer->getWorld()->getMaxY()) - 8;
+		$minY = min($origin->getFloorY(), $world->getMaxY()) - 8;
```
Comment (IvanCraft623) [inline src/item/ChorusFruit.php]: Unrelated change

Comment (DebHugo) [reply src/item/ChorusFruit.php]: I know but I think opening a pull request just for that is kinda pointless

Comment (dktapps) [reply src/item/ChorusFruit.php]: Changing it is also kind of pointless, so don't make your PR a pain in the ass by adding unrelated changes to it

**Review by ShockedPlot7560 — APPROVED** [review]
