### PR TITLE
BlockObjectToStateSerializer: Avoid unnecessary Writer and Closure

### LINKED ISSUE #6675: BlockObjectToStateSerializer: Allow serializers to return an ID string directly instead of a BlockStateWriter instance
### Link to crashdump

https://crash.pmmp.io/view/12462321

### Additional comments (optional)

Most common blocks don't need to store any properties. In these cases we can avoid redundant object allocations by allowing the serializer handlers to just return IDs directly.

This crashdump was likely caused by a mistake, but the idea is a good one.

### PR DESCRIPTION
**Pull request by ShockedPlot7560**
In the case of a simple mapping for the block serializer, we don't even need to go through `BlockStateWriter` to get the `BlockStateData`.

This PR, as the issue suggests, allows the serializer to return a string directly instead of a Writer in order to limit the allocation of unnecessary objects.

### Related issues & PRs
* fixes #6675 

### API changes
- Serializers in `BlockObjectToStateSerializer` can now return a string safely.

### CODE REVIEW

**Comment by dktapps** [comment]
I did look at doing this myself, but since we already cache state IDs in this case anyway, the benefit is fairly minimal. It does allow us to have less useless closures and such, but the performance benefit is close to 0.

Edit: I see this goes further than I originally envisioned. I hadn't thought about getting rid of `Writer` for switched IDs with no states.

File: src/data/bedrock/block/convert/BlockObjectToStateSerializer.php [hunk 1]
```diff
@@ -243,7 +243,7 @@ public function map(Block $block, \Closure $serializer) : void{
 	}
 
 	public function mapSimple(Block $block, string $id) : void{
-		$this->map($block, fn() => Writer::create($id));
+		$this->map($block, fn() => $id);
```
Comment (dktapps) [inline src/data/bedrock/block/convert/BlockObjectToStateSerializer.php]: This doesn't make much sense, it would be better if we could ditch the closure entirely

Comment (ShockedPlot7560) [reply src/data/bedrock/block/convert/BlockObjectToStateSerializer.php]: Yeah, that's was my second intention, it will be done in this PR instead of a follow up

File: src/data/bedrock/block/convert/BlockObjectToStateSerializer.php [hunk 2]
```diff
@@ -277,14 +278,20 @@ public function serializeBlock(Block $blockState) : BlockStateData{
 		 * the type ID of the block (which never makes sense, even in a world where overriding block types is a thing).
 		 * In the future we'll need some way to guarantee that type IDs are never reused (perhaps spl_object_id()?)
 		 *
-		 * @var \Closure $serializer
-		 * @phpstan-var \Closure(TBlockType) : Writer $serializer
+		 * @var \Closure|string $serializer
+		 * @phpstan-var \Closure(TBlockType) : (Writer|string)|string $serializer
 		 */
 		$serializer = $locatedSerializer;
+		if(is_callable($serializer)){
```
Comment (dktapps) [inline src/data/bedrock/block/convert/BlockObjectToStateSerializer.php]: `instanceof \Closure` would be better here, a string ID might be incorrectly considered callable

Comment (dktapps) [reply src/data/bedrock/block/convert/BlockObjectToStateSerializer.php]: This can also be reduced to a ternary

Comment (dktapps) [reply src/data/bedrock/block/convert/BlockObjectToStateSerializer.php]: Actually this whole thing can be simplified

**Comment by dktapps** [comment]
Are there any situations where we return a `Writer` without taking any info from the `Block`?

**Comment by ShockedPlot7560** [comment]
> Are there any situations where we return a `Writer` without taking any info from the `Block`?

I've gone through everything and normally there shouldn't be any more, subject to error but low risk.

**Comment by dktapps** [comment]
The code you've written would allow for `Writer|string` or `Closure(Block) : (Writer|string)` if we wanted it to. So I'm just wondering if there's any cases where we write properties that aren't derived from the block (e.g. to polyfill and make Minecraft happy).

**Comment by dktapps** [comment]
https://github.com/pmmp/PocketMine-MP/blob/stable/src/data/bedrock/block/convert/BlockObjectToStateSerializer.php#L594
https://github.com/pmmp/PocketMine-MP/blob/a83c62a4a2e5eea17fdfc3eb2bfd55f31534a9e3/src/data/bedrock/block/convert/BlockObjectToStateSerializer.php#L1282-L1283
https://github.com/pmmp/PocketMine-MP/blob/a83c62a4a2e5eea17fdfc3eb2bfd55f31534a9e3/src/data/bedrock/block/convert/BlockObjectToStateSerializer.php#L1629-L1630
https://github.com/pmmp/PocketMine-MP/blob/a83c62a4a2e5eea17fdfc3eb2bfd55f31534a9e3/src/data/bedrock/block/convert/BlockObjectToStateSerializer.php#L1706
https://github.com/pmmp/PocketMine-MP/blob/a83c62a4a2e5eea17fdfc3eb2bfd55f31534a9e3/src/data/bedrock/block/convert/BlockObjectToStateSerializer.php#L1714

All of these cases could be mapped to a `Writer` instance directly (or `BlockStateData`) since they don't use the block input for context. If you ctrl+f for `fn() =>` there's probably more cases.

**Comment by ShockedPlot7560** [comment]
I see our point of view, it is necessary to define the serialiser as `Closure|string|Writer` to cover all cases. Good catch

**Comment by dktapps** [comment]
I've been thinking about this, and I'm not sure that going to `string` actually makes sense. Since we turn it into `BlockStateData` before returning it anyway, and there are cases where we just want to return a static `BlockStateData` anyway.

Perhaps it would make more sense to just have `BlockStateData|\Closure(Block) : (Writer|BlockStateData)`.

**Comment by ShockedPlot7560** [comment]
I'm not sure at the moment about using BlockStateData::current and getBlockStateData directly in this class. Looks weird for me.

I'm still dubious about the use of BlockStateData rather string in the sense that the changes there are aimed more at reducing the memory footprint than overall performance. By replacing Writer with BlockStateData, there's no real gain, so do we really need this change?

**Comment by dktapps** [comment]
I've tidied this up. There are now the following cases:

- Closure(Block) -> Writer (regular case)
- Closure(Block) -> BlockStateData (block with flattened IDs, no state data)
- Writer (polyfills useless properties, not dependent on input)
- BlockStateData (ID only, not dependent on input)

Though I want to rethink the way flattened IDs are handled at some point

**Review by dktapps — APPROVED** [review]
