### PR TITLE
Strip unnecessary NBT from network items

### LINKED ISSUE #4665: You can install a block with any NBT length by clicking on the interactive block
### Issue description
If you get the same item as in #4664, then you can place it by clicking on the interactive blocks. If you spam with clicks, the server will crash from lack of RAM 

- Expected result: Chest is not placed 
- Actual result: Server crashes 

### Steps to reproduce the issue
1. Turn on creative mode 
2. Place the chest
3. Copy it by pressing the mouse wheel and the control key 
4. Put the received item in the chest
5. Repeat steps several times
6. Spam by installing this chest on interactive blocks 
7. Server crashed 

### OS and versions

* PocketMine-MP: 4.0.3 795ebd182461f96beeb47b067f7fe33e76bc9059
* PHP: 8.0.12
* Using JIT: no
* Server OS: win

### Plugins
none

### Crashdump, backtrace or other files
[Sat_Dec_18-20.33.36-CAT_2021.log](https://github.com/pmmp/PocketMine-MP/files/7739756/Sat_Dec_18-20.33.36-CAT_2021.log)

### PR DESCRIPTION
**Pull request by dktapps**
Item containers like shulker boxes, or chests with block entity data obtained with ctrl+middle click, will often have extremely large NBT payloads. This problem gets exponentially worse in cases where it's possible to nest inventories, as in #4665.

We can't easily address this at the core level, because tiles are not able to exist within items (due to position requirement) so we don't have a good way to avoid this useless NBT in the first place. However, we can strip it before the item is sent to the client, which dramatically reduces the network costs of such items, as well as removing any reason the client could have to send such enormous items to the server.

A fully loaded shulker box with written books now takes only 5-6 KB on the wire instead of ~1 MB, which is a substantial improvement.

Dealing with this in a less hacky way is currently blocked on #6147.

### Related issues & PRs
- Fixes #4665 
- Fixes, kinda, #6649 , although this needs to be redone in a better way once #6147 is dealt with

### API changes
None

### Behavioural changes
Significant network performance improvement when dealing with items containing inventories or block entity data (containing inventories)
Pains were taken to ensure that the lore of shulker boxes doesn't break with this change, however it is possible I may have missed something. Nonetheless, I think this change is worth it.

## Backwards compatibility
Backwards compatible

## Follow-up
Redo this in PM6 once #6149 is done

## Tests
Playtested with shulkerboxes and nested chests

### CODE REVIEW

File: src/network/mcpe/convert/TypeConverter.php [hunk 1]
```diff
@@ -197,6 +206,90 @@ public function netRecipeIngredientToCore(ProtocolRecipeIngredient $ingredient)
...
+	 * NBT but different server-side NBT.
+	 */
+	protected function hashNBT(Tag $tag) : string{
+		$encoded = (new LittleEndianNbtSerializer())->write(new TreeRoot($tag));
+		return hash('sha256', $encoded, binary: true);
+	}
+
+	/**
+	 * TODO: HACK!
+	 * Strips non-viewable data from the NBT of an item.
```
Comment (dries-c) [inline src/network/mcpe/convert/TypeConverter.php]: it strips it of a copy of the item, might be nice to include that in the doc

File: src/network/mcpe/convert/TypeConverter.php [hunk 2]
```diff
@@ -197,6 +206,90 @@ public function netRecipeIngredientToCore(ProtocolRecipeIngredient $ingredient)
...
 
+	/**
+	 * Strips unnecessary block actor NBT from items that have it.
+	 * This tag can potentially be extremely large, and is not read by the client anyway.
+	 */
+	protected function stripBlockEntityNBT(CompoundTag $tag) : bool{
+		if(
+			($blockEntityTag = $tag->getTag(Item::TAG_BLOCK_ENTITY_TAG)) !== null &&
+			$blockEntityTag instanceof CompoundTag &&
+			$blockEntityTag->count() > 0
```
Comment (dries-c) [inline src/network/mcpe/convert/TypeConverter.php]: Does it make a difference if it's an empty CompoundTag?

Comment (dktapps) [reply src/network/mcpe/convert/TypeConverter.php]: Yeah, we don't want to put a hash of the full NBT in the item if it wasn't modified

**Review by dries-c — APPROVED** [review]
