### PR TITLE
Fixed desynchronization of hunger

### LINKED ISSUE #2728: Starvation is client-side
### Issue description
When i cancelled PlayerItemConsumeEvent, client still increases food bar

### Steps to reproduce the issue
1. Cancel PlayerItemConsumeEvent
2. Look at food bar

### OS and versions

* PocketMine-MP: 3.5.x
* PHP: 7.2
* Server OS: Windows 10
* Game version: Win10

### Possible solution:
Sending hunger attribute when event is cancelled

### PR DESCRIPTION
**Pull request by JavierLeon9966**
## Introduction

Currently when you cancel `PlayerItemConsumeEvent` it doesn’t synchronize the hunger bars to the player. This pull request aims to fix that.
### Relevant issues

* Fixes #2728
### API changes

None
### Behavioural changes

The server now synchronizes the hunger bars to the player when `PlayerItemConsumeEvent` gets cancelled or `Living->consumeObject()` returns false.
## Backwards compatibility

None
## Follow-up

None
## Tests

```php
<?php

declare(strict_types = 1);

namespace JavierLeon9966\HungerTest;

use pocketmine\event\EventPriority;
use pocketmine\event\player\PlayerItemConsumeEvent;
use pocketmine\plugin\PluginBase;

class Main extends PluginBase{
    public function onEnable(): void{
        $this->getServer()->getPluginManager()->registerEvent(PlayerItemConsumeEvent::class, static fn(PlayerItemConsumeEvent $event) => $event->cancel(), EventPriority::HIGHEST, $this);
    }
}
```
https://user-images.githubusercontent.com/58715544/147900890-d66258a1-08ad-4c24-ab1a-b27897048f6b.mp4

### CODE REVIEW

File: src/network/mcpe/handler/InGamePacketHandler.php [hunk 1]
```diff
@@ -371,6 +372,8 @@ private function handleUseItemTransaction(UseItemTransactionData $data) : bool{
 			case UseItemTransactionData::ACTION_CLICK_AIR:
 				if($this->player->isUsingItem()){
 					if(!$this->player->consumeHeldItem()){
+						$hungerAttr = $this->player->getAttributeMap()->get(Attribute::HUNGER) ?? throw new AssumptionFailedError();
+						$this->session->syncAttributes($this->player, [$hungerAttr]);
```
Comment (dktapps) [inline src/network/mcpe/handler/InGamePacketHandler.php]: `markSynchronized(false)` would suit better, so that it gets synced together with other attributes at the end of the tick.

Comment (JavierLeon9966) [reply src/network/mcpe/handler/InGamePacketHandler.php]: Done

File: src/network/mcpe/handler/InGamePacketHandler.php [hunk 2]
```diff
@@ -371,6 +372,8 @@ private function handleUseItemTransaction(UseItemTransactionData $data) : bool{
 			case UseItemTransactionData::ACTION_CLICK_AIR:
 				if($this->player->isUsingItem()){
 					if(!$this->player->consumeHeldItem()){
+						$hungerAttr = $this->player->getAttributeMap()->get(Attribute::HUNGER) ?? throw new AssumptionFailedError();
```
Comment (dktapps) [inline src/network/mcpe/handler/InGamePacketHandler.php:375]: You can use `mustGet()` in here and avoid the AssumptionFailedError.
