### PR TITLE
Removed masks for Y coordinates, throw exception for block hash Y out of bounds, fixed #914

### LINKED ISSUE #914: Water flow wraps around to the top of the world when falling into the void
### Issue description

 Hey guys! I just found some crazy bug that needs to be fixed.. so if water fall to void it will spawn back to sky.. i got some photos if you do not understand what i mean..

### Steps to reproduce the issue

1. ... 
2. ...

### OS and versions

* PocketMine-MP: PocketMine-MP 1.6.2dev-76
* PHP: 3.0.0
* Server OS: Minecraft: PE v1.0.7.0 (protocol version 107)
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

http://imgur.com/a/jEpyE
http://imgur.com/a/0u4eC
* ...

### PR DESCRIPTION
**Pull request by dktapps**
## Introduction
These masks produced many unexpected behaviours relating to Y coordinates out of bounds, like #914.

This PR carries changes required to fix this issue, along with several others. Adding an exception throw for out-of-bounds Y coordinates for block hashes uncovered several wraparound problems, such as:

- Flying below y=0 would cause block collision checks for blocks up at y=~250
- Breaking blocks at y=0 would trigger block updates at the top of the map.

This may also cause other crashy issues which I haven't identified yet, so this needs careful testing before merging.

### Relevant issues
- fixes #914

### API changes
- Added `addToCache` parameter to `Level->getBlock()` to allow plugin developers to choose to not cache the returned block object if they are making frequent requests to the method. This may mitigate issues with block-cache issues like #152 .

### Behavioural changes
- An exception will now be thrown when attempting to create a block coordinate hash with an invalid Y coordinate.
- bugs fixed above

### CODE REVIEW

File: src/pocketmine/level/Level.php [hunk 1]
```diff
@@ -1274,22 +1276,43 @@ public function getFullBlock(int $x, int $y, int $z) : int{
...
+	}
+
+	/**
+	 * Gets the Block object at the Vector3 location
 	 *
 	 * @param Vector3 $pos
-	 * @param bool    $cached
+	 * @param bool    $cached Whether to use the block cache for getting the block (faster, but may be inaccurate)
+	 * @param bool    $addToCache Whether to cache the block object created by this method call.
+	 *                             Note for plugin developers: If you are using this method a lot (thousands of times for many positions), you may want to set this to false to avoid using excessive amounts of memory.
```
Comment (Sandertv) [inline src/pocketmine/level/Level.php]: That's awesome. Thanks for that @dktapps.

File: src/pocketmine/level/Level.php [hunk 2]
```diff
@@ -1069,12 +1072,11 @@ public function scheduleDelayedBlockUpdate(Vector3 $pos, int $delay){
...
 
-		$this->neighbourBlockUpdateQueue->enqueue(Level::blockHash($pos->x + 1, $pos->y, $pos->z));
-		$this->neighbourBlockUpdateQueue->enqueue(Level::blockHash($pos->x - 1, $pos->y, $pos->z));
-		$this->neighbourBlockUpdateQueue->enqueue(Level::blockHash($pos->x, $pos->y + 1, $pos->z));
-		$this->neighbourBlockUpdateQueue->enqueue(Level::blockHash($pos->x, $pos->y - 1, $pos->z));
-		$this->neighbourBlockUpdateQueue->enqueue(Level::blockHash($pos->x, $pos->y, $pos->z + 1));
-		$this->neighbourBlockUpdateQueue->enqueue(Level::blockHash($pos->x, $pos->y, $pos->z - 1));
+		for($i = 0; $i <= 5; ++$i){
+			if($this->isInWorld($s = $pos->getSide($i))){
+				$this->neighbourBlockUpdateQueue->enqueue(Level::blockHash($pos->x, $pos->y, $pos->z));
```
Comment (jasonwynn10) [inline src/pocketmine/level/Level.php]: Why is this not using `$s` instead of `$pos`?

Comment (dktapps) [inline src/pocketmine/level/Level.php]: Thanks.

**Comment by dktapps** [comment]
preprocessor is going to be a problem...

**Comment by dktapps** [comment]
I guess for optimized builds the exception throw is not strictly necessary.
