### PR TITLE
 Lava burns entities for only 8 seconds

### LINKED ISSUE #5172: Lava combusts entities for an incorrect amount of time
### Issue description
In Bedrock, lava burns entities for only 8 seconds, whereas PM burns them for 15. I assume this is another parity inconsistency between Java and Bedrock.

### Steps to reproduce the issue
1. Step into lava and back out
2. Notice you burn for 15 seconds instead of the expected 8

### OS and versions

* PocketMine-MP: 4.6.0 / 5.0.0-ALPHA2

### PR DESCRIPTION
**Pull request by IvanCraft623**
## Introduction

Set the time that entities are burned by lava according to vanilla bedrock.

### Relevant issues

* Fixes #5172

### Behavioural changes

Lava burns entities for less time

### CODE REVIEW

File: src/block/Lava.php [hunk 1]
```diff
@@ -94,7 +94,8 @@ public function onEntityInside(Entity $entity) : bool{
 		$ev = new EntityDamageByBlockEvent($this, $entity, EntityDamageEvent::CAUSE_LAVA, 4);
 		$entity->attack($ev);
 
-		$ev = new EntityCombustByBlockEvent($this, $entity, 15);
+		//in java burns entities for 15 seconds - seems to be a parity issue in bedrock
```
Comment (dktapps) [inline src/block/Lava.php:97]: have you verified this?

Comment (IvanCraft623) [reply src/block/Lava.php:97]: Yes, minecraft java:

https://user-images.githubusercontent.com/57236932/179421901-d7e5a7ea-1d11-4504-b39a-f63482351eaf.mp4
