### PR TITLE
Workaround for offhand sync

### LINKED ISSUE #4231: Offhand inventory doesn't sync slots on master branch
### Issue description

- Expected result: when I expect to die in-game, the totem must disappear from the second hand after being consumed
- Actual result: totem doesn't disappear, but when I try to take it, it disappears.

### Steps to reproduce the issue
1. /gamemode 0
2. put totem in offhand slot
3. try to die

### OS and versions

* PocketMine-MP: master 2f51ed83a48c6a650743c22743458ae2b49411c5
* PHP: 8.0.5 (cli) (built: May  1 2021 17:03:16)
* Server OS: Windows 10 (10.0.19042)
* Game version: Win10

### No plugins
But this issue can be solved using this *hack*
```php
//PlayerOffHandInventory
//override onSlotChange
protected function onSlotChange(int $index, Item $before): void {
    foreach($this->listeners as $listener){
        $listener->onSlotChange($this, $index, $before);
    }
    foreach($this->viewers as $viewer){
        $viewer->getNetworkSession()->getInvManager()->syncContents($this);
        //$viewer->getNetworkSession()->getInvManager()->syncSlot($this, $index);
    }
}
```

https://user-images.githubusercontent.com/32373441/119360510-5c619900-bcb3-11eb-8eea-81953d1bc683.mp4

### PR DESCRIPTION
**Pull request by Rush2929**
## Introduction

Offhand slots sometimes ignore Inventory Slot Packets.
### Relevant issues

* Fix #4231 

### Behavioural changes

Send InventoryContentPacket as a workaround.

## Tests

https://user-images.githubusercontent.com/76860328/128989052-edf5584e-eef4-4803-b312-219732f14299.mp4

### CODE REVIEW

File: src/network/mcpe/InventoryManager.php [hunk 1]
```diff
@@ -209,11 +209,11 @@ public function syncSlot(Inventory $inventory, int $slot) : void{
 			$currentItem = $inventory->getItem($slot);
 			$clientSideItem = $this->initiatedSlotChanges[$windowId][$slot] ?? null;
 			if($clientSideItem === null or !$clientSideItem->equalsExact($currentItem)){
-				$typeConverter = TypeConverter::getInstance();
+				$itemStackWrapper = ItemStackWrapper::legacy(TypeConverter::getInstance()->coreItemStackToNet($currentItem));
 				if($windowId === ContainerIds::OFFHAND){
```
Comment (dktapps) [inline src/network/mcpe/InventoryManager.php:213]: Please add a `TODO: HACK!` comment about this with a brief explanation why it's needed.
