### PR TITLE
Better sorting of items in InventoryHelpersTrait::addItem()

### LINKED ISSUE #1412: BaseInventory->addItem() with a list of separate, stackable items puts each stack in its own slot
### Issue description
```
$inventory->addItem(
    Item::get(Item::PLANKS, 0, 16),
    Item::get(Item::PLANKS, 0, 16),
    Item::get(Item::PLANKS, 0, 16),
    Item::get(Item::PLANKS, 0, 16)
);
```
will put each of the stacks in a separate slot instead of combining them as expected.

### Steps to reproduce the issue

1. use the above code
2. profit

### PR DESCRIPTION
**Pull request by jasonw4331**
## Introduction

Dylan posted an issue on it, so its getting changed.

### Relevant issues

Fixes #1412

### API changes

`InventoryHelpersTrait::addItem()` will now stack items together even when provided separately as parameters.

### Behavioral changes

N/A

## Backwards compatibility

N/A

## Follow-up

N/A

## Tests

```php
$inventory->addItem(
	VanillaBlocks::OAK_PLANKS()->asItem()->setCount(16),
	VanillaBlocks::OAK_PLANKS()->asItem()->setCount(16),
	VanillaBlocks::OAK_PLANKS()->asItem()->setCount(16),
	VanillaBlocks::OAK_PLANKS()->asItem()->setCount(16)
);
```

image

### CODE REVIEW

**Comment by dktapps** [comment]
To be honest, I think a better solution is to just separate the logic of addItem() into an internal method, and then call the internal method once for each argument. That would guarantee consistency with minimal changes.

**Comment by jasonwynn10** [comment]
Is that closer to what you're talking about?

File: src/inventory/InventoryHelpersTrait.php [hunk 1]
```diff
@@ -168,43 +163,32 @@ public function addItem(Item ...$slots) : array{
...
-
-			if(count($itemSlots) === 0){
-				break;
-			}
 		}
 
-		if(count($itemSlots) > 0 and count($emptySlots) > 0){
+		if(count($emptySlots) > 0){
 			foreach($emptySlots as $slotIndex){
 				//This loop only gets the first item, then goes to the next empty slot
```
Comment (dktapps) [inline src/inventory/InventoryHelpersTrait.php:181]: The loop that this comment describes no longer exists.

**Comment by dktapps** [comment]
Please write a PHPUnit test for this.

File: src/inventory/InventoryHelpersTrait.php [hunk 2]
```diff
@@ -144,6 +144,17 @@ public function addItem(Item ...$slots) : array{
 			}
 		}
 
+		/** @var Item[] $returnSlots */
+		$returnSlots = [];
+
+		foreach($itemSlots as $item){
+			$returnSlots[] = $this->internalAddItem($item);
```
Comment (dktapps) [inline src/inventory/InventoryHelpersTrait.php:151]: This should check if the returned item `isNull()`, and don't add it to the result if so.

**Review by dktapps — CHANGES_REQUESTED** [review]
This PR should include unit tests to show that the behaviour is as expected (the behaviour of addItem(1, 2, 3, 4) should be the same as 4 separate addItem() calls).

**Review by dktapps — APPROVED** [review]
