### PR TITLE
Fix #5471: Use pocketmine. prefixed key for spawnpoint success

### LINKED ISSUE #5471: `commands.spawnpoint.success` missing client-side translation
### Issue description
As per title. This needs to be either updated to whatever the new vanilla string is, or a `pocketmine.` prefixed replacement needs to be added.

### Steps to reproduce the issue
1. Invoke `/spawnpoint` as an operator player
2. Notice the output message

### OS and versions

* PocketMine-MP: 4.12.2

### PR DESCRIPTION
**Pull request by siyFred**
Closes #5471. This moves the spawnpoint success message to a pocketmine. namespaced key.

### CODE REVIEW

File: src/lang/KnownTranslationFactory.php [hunk 1]
```diff
@@ -450,7 +450,7 @@ public static function commands_setworldspawn_usage() : Translatable{
 	}
 
 	public static function commands_spawnpoint_success(Translatable|string $param0, Translatable|string $param1, Translatable|string $param2, Translatable|string $param3) : Translatable{
-		return new Translatable(KnownTranslationKeys::COMMANDS_SPAWNPOINT_SUCCESS, [
+		return new Translatable(KnownTranslationKeys::POCKETMINE_COMMAND_SPAWNPOINT_SUCCESS, [
```
Comment (dktapps) [inline src/lang/KnownTranslationFactory.php]: This file is auto generated

File: src/lang/KnownTranslationKeys.php [hunk 2]
```diff
@@ -378,9 +377,10 @@ final class KnownTranslationKeys{
 	public const POCKETMINE_COMMAND_SAVEON_DESCRIPTION = "pocketmine.command.saveon.description";
 	public const POCKETMINE_COMMAND_SAY_DESCRIPTION = "pocketmine.command.say.description";
 	public const POCKETMINE_COMMAND_SEED_DESCRIPTION = "pocketmine.command.seed.description";
-	public const POCKETMINE_COMMAND_SETWORLDSPAWN_DESCRIPTION = "pocketmine.command.setworldspawn.description";
+  public const POCKETMINE_COMMAND_SETWORLDSPAWN_DESCRIPTION = "pocketmine.command.setworldspawn.description";
 	public const POCKETMINE_COMMAND_SPAWNPOINT_DESCRIPTION = "pocketmine.command.spawnpoint.description";
-	public const POCKETMINE_COMMAND_STATUS_DESCRIPTION = "pocketmine.command.status.description";
+  public const POCKETMINE_COMMAND_SPAWNPOINT_SUCCESS = "pocketmine.command.spawnpoint.success";
+  public const POCKETMINE_COMMAND_STATUS_DESCRIPTION = "pocketmine.command.status.description";
```
Comment (dktapps) [inline src/lang/KnownTranslationKeys.php]: This file is also auto generated

File: resources/translations/eng.ini [hunk 3]
```diff
@@ -374,6 +374,7 @@ pocketmine.command.say.description=Broadcasts the given message as the sender
 pocketmine.command.seed.description=Shows the world seed
 pocketmine.command.setworldspawn.description=Sets a world's spawn point. If no coordinates are specified, the player's coordinates will be used.
 pocketmine.command.spawnpoint.description=Sets a player's spawn point
+pocketmine.command.spawnpoint.success=Set {%0}'s spawn point to ({%1}, {%2}, {%3})
```
Comment (dktapps) [inline resources/translations/eng.ini:376]: You should remove the old string since it no longer works
Also the old key should be removed from `known-bad-keys.json`

**Review by dktapps — CHANGES_REQUESTED** [review]

File: resources/translations/known-bad-keys.json [hunk 4]
```diff
@@ -1,69 +1,68 @@
...
-    "server_properties",
-    "setting_up_server_now",
-    "skip_installer",
-    "view_distance",
-    "welcome_to_pocketmine",
-    "whitelist_enable",
-    "whitelist_info",
-    "whitelist_warning",
-    "you_have_finished",
-    "you_have_to_accept_the_license"
```
Comment (dktapps) [inline resources/translations/known-bad-keys.json:68]: The indentation of this file should not be changed

**Review by dktapps — DISMISSED** [review]

**Comment by dktapps** [comment]
Thanks!

**Comment by siyFred** [comment]
I really appreciate all the guidance. This was my very first open-source contribution ever, so I learned a lot from the whole process. Thanks for your patience! See you around.
