### PR TITLE
Might fix #104 

### LINKED ISSUE #104: Console becomes unresponsive after several hours idle.
### Issue description
On both PocketMine-MP_1.6.1dev-73_794ff643_API-2.1.0 and PocketMine-MP_1.6.1dev-76_8214e50b_API-2.1.0, (Windows 10 Pro) after two or more hours of operation, unattended with no players in the game, upon returning to the console there is no response to commands.  The game is still functioning, players may login and the world responds normally.  However, at the console (the server terminal window), commands such as "list" or "version" are ignored.  Characters typed appear on the screen, but without effect.  Ctrl-C is recognized, terminating the program.

### Steps to reproduce the issue

1. start.cmd
2. verify operation of console (terminal window) by issuing "version" command.
3. verify game operation by briefly logging in from Windows Phone 8.1 device.
4. exit device from game.
5. leave system idle for two hours.
6. attempt "version" command again.
7. verify game operation by logging in from gaming device.

### OS and versions
[23:37:31] [Server thread/INFO]: This server is running PocketMine-MP 1.6.1dev-#76 「Unleashed」 implementing API version 2.1.0 for Minecraft: PE v0.16.0.5 alpha (protocol version 91)

* Title Bar:  PocketMine-MP 1.6.1dev-#76 | Online 0/20 | Memory 16.11/0/16.11/20 MB @ 6 threads | U 0 D 0 kB/s | TPS 20 | Load 0.28%

* PocketMine-MP:   PocketMine-MP_1.6.1dev-76_8214e50b_API-2.1.0

* PHP: PHP7.0.13

* Server OS:  Windows 10 Pro

* Game version: PE

### Crashdump, backtrace or other files

* ...

### PR DESCRIPTION
**Pull request by robske110**
This PR tries to fix #104, through reopening stdin on corruption.
It also closes stdin on shutdown.

~This is untested due to the lack of access to a windows OS for me currently.~

### CODE REVIEW

File: src/pocketmine/command/CommandReader.php [hunk 1]
```diff
@@ -91,6 +95,8 @@ public function run(){
 
 			$lastLine = microtime(true);
 		}
+		global $stdin;
+		fclose($stdin);
```
Comment (dktapps) [inline src/pocketmine/command/CommandReader.php]: bad idea doing this here without any checks.

**Comment by KAGsundaram** [comment]
Later today I expect to run a test for robske110.  (See my comment at [#104](https://github.com/pmmp/PocketMine-MP/issues/104))

File: src/pocketmine/command/CommandReader.php (hunk 1 above)
Comment (robske110) [inline src/pocketmine/command/CommandReader.php]: well, stdin _should_ not be no resource

**Comment by KAGsundaram** [comment]
Testing https://github.com/robske110/pmmp-PocketMine-MP/tree/patch-1

Should detailed comments be here or at #104 ?

File: src/pocketmine/command/CommandReader.php [hunk 2]
```diff
@@ -91,6 +95,10 @@ public function run(){
 
 			$lastLine = microtime(true);
 		}
+		global $stdin;
+		if(is_resource($stdin)){
+			fclose($stdin);
+		}
```
Comment (robske110) [inline src/pocketmine/command/CommandReader.php]: Yup, you're right :)

Comment (KAGsundaram) [inline src/pocketmine/command/CommandReader.php]: seen

Comment (robske110) [inline src/pocketmine/command/CommandReader.php]: What?

Comment (KAGsundaram) [inline src/pocketmine/command/CommandReader.php]: robske110, I was indicating that I had seen and was following with interest your conversation with dktapps.

Comment (SOF3) [inline src/pocketmine/command/CommandReader.php]: @KAGsundaram you could use GitHub comment reactions. They can prevent this from occupying UI space or sending unnecessary notifications to other people.

**Comment by robske110** [comment]
I'm still working on this, trying to figure stuff out.

**Comment by robske110** [comment]
This is confirmed to work, Status: Insufficiently tested can be removed

**Comment by robske110** [comment]
fail.

File: src/pocketmine/command/CommandReader.php [hunk 3]
```diff
@@ -34,21 +35,36 @@ public function __construct(){
 		$opts = getopt("", ["disable-readline"]);
 		$this->readline = (extension_loaded("readline") and !isset($opts["disable-readline"]));
 		$this->start();
+		echo(\pocketmine\PATH);
```
Comment (SOF3) [inline src/pocketmine/command/CommandReader.php]: Remove this?

File: src/pocketmine/command/CommandReader.php [hunk 4]
```diff
@@ -34,21 +35,36 @@ public function __construct(){
...
+		$this->getClassLoader()->addPath(\pocketmine\PATH . "src");
```
Comment (SOF3) [inline src/pocketmine/command/CommandReader.php]: I think the class loader already has this path. I think only register() is necessary.

**Comment by robske110** [comment]
This can be re-reviewed now, it is confirmed to fix #104

File: src/pocketmine/command/CommandReader.php [hunk 5]
```diff
@@ -40,15 +41,27 @@ public function shutdown(){
...
 			if(!is_resource($stdin)){
-				return "";
+				$this->initStdin();
 			}
-
-			return trim(fgets($stdin));
+			
+			$fgets = fgets($stdin);
+			
+			if(Utils::getOS() == "win" && $fgets === false){ //windows sucks
```
Comment (dktapps) [inline src/pocketmine/command/CommandReader.php]: I find it unlikely that this issue only ever occurs on Windows. This I think is a bad idea.

Comment (dktapps) [inline src/pocketmine/command/CommandReader.php]: This is an issue corresponding to the issue reported at #25 , which has also been observed on various platforms, although _mostly_ on Windows.

Comment (robske110) [inline src/pocketmine/command/CommandReader.php]: Well, this will only fix it for windows until i find a genius way to do this. I could use some time() statements, but that doesn't sound like a good practise!

**Comment by dktapps** [comment]
Would anybody like to re-test this with the latest commit?

**Comment by robske110** [comment]
I'll try to
